### ISSUE TITLE
utils.api.product.getById() response content-type has been changed

### ISSUE THREAD

**Issue by tvlgiao** [bigcommerce/stencil-utils#102]
Please check this store and the ajax request in Web Developer tool:
https://chiara-furniture-demo.mybigcommerce.com/hemnes-shoe-cabinet/

The response content-type has been changed from **text/html** to **text/plain**.
http://prntscr.com/nqvkkj
http://prntscr.com/nqvla0

Which causes error when parsing JSON data in **stencil-utils/lib/request.js** line 110
http://prntscr.com/nqvlxd
http://prntscr.com/nqvnsc

It affects some themes using getById() with template sections.

**Comment by bookernath** [comment]
Thanks for the report @tvlgiao ! We'll take a look and report back.

**Comment by bookernath** [comment]
This should be fixed now. Please let us know if you continue to see issues!

**Comment by tvlgiao** [comment]
Hi @bookernath 

It seems to happen again today.

Please check this screenshot I tested with postman: 
http://prntscr.com/nuuyfs
http://prntscr.com/nuuz25

You can import this request to postman to test:
https://gist.github.com/tvlgiao/9229b3d3b662c2e0a81ea7612c96dfd5

I suppose the error appeared from products.php script, not stencil-utils.

**Comment by mattolson** [comment]
@tvlgiao I'm looking into this now, thanks for the report.

**Comment by mattolson** [comment]
@tvlgiao The problem has been resolved. Thank you for the report, and for your patience.
