### ISSUE TITLE
Add to Cart button on product page not firing itemAdd script using stencil-utils 6.12.0

### ISSUE THREAD

**Issue by lilshef** [bigcommerce/stencil-utils#178]
### Expected behavior
Clicking the Add to Cart button should trigger the overlay, the preview modal and add the item to the cart.

### Actual behavior
Clicking the Add to Cart button only updates the button text and does not add the item to the cart or trigger the preview modal.

### Steps to reproduce behavior
Download the latest version of Cornerstone, at this time is 6.5.0, and install. Connect to any store and go to any product and try to add to cart.

### Additional Notes
I was able to revert back to previous versions of stencil-utils and confirmed the product added to the cart. I tested this on both stencil-utils versions 6.8.1 and 6.11.0. Tested on multiple computers and different clients and found the issue to be consistent with the latest stencil-utils version.

Stencil-cli version `stencil --version`: 5.2.0

Node version `node -v`: 14.15.0

NPM version `npm -v`: 6.14.8

**Comment by adrianFour13** [comment]
I am also experience this issue with stencil-utils 6.12.0 and it does not work on one of our projects. I tried reverting it to 6.11.0 and it works.

**Comment by jordanarldt** [comment]
@lilshef @adrianFour13 
Thank you for bringing up this issue. We've released a fix in 6.12.1, so I'll go ahead and close out this issue.
