### ISSUE TITLE
Default export not working properly

### ISSUE THREAD

**Issue by flyingL123** [bigcommerce/stencil-utils#63]
I'm not sure what I'm missing here:

```
import hooks from './hooks';
import api from './api';
import tools from './tools';

const StencilUtils = {
    hooks: hooks,
    api: api,
    tools: tools,
};

export {hooks, api, tools};
export default StencilUtils;

/* global define */
(function(root) {
    if (typeof define === 'function' && define.amd) {
        define(function() {
            return (root.stencilUtils = StencilUtils);
        });
    } else if (typeof module === 'object' && module.exports) {
        module.exports = StencilUtils;
    } else {
        window.stencilUtils = StencilUtils;
    }
}(this));
```

Then, in `assets/js/theme/common/product-details.js`:

```
import utils from 'bigcommerce/stencil-utils';

utils.hooks.on('cart-item-add', (event, form) => {
    // do stuff
});
```

When the files load, I get an error that `utils` is `undefined`. If I change the file to this:

```
import {hooks} from 'bigcommerce/stencil-utils';

hooks.on('cart-item-add', (event, form) => {
    // do stuff
});
```

It works correctly. So, it appears something is not working correctly with the default export statement. Is there something obviously wrong here with the import or export statements that would cause this issue?

**Comment by hegrec** [comment]
You should be importing from `@bigcommerce/stencil-utils` instead of `bigcommerce/stencil-utils` You can see an example in the base theme which is working on our end. For future questions, please see the developer help forum here: https://developer.bigcommerce.com/help/ because github issues is not monitored very often by our team

**Comment by steve-ross** [comment]
Also the docs need updating (in the README.md):
"Import the library import utils from `'bigcommerce/stencil-utils';` in modules that depend on it."

**Comment by davidwrpayne** [comment]
Closing this as the Author was responded to back in 2016. I assume this is no longer an issue. Please respond if this isn't the case.
