### ISSUE TITLE
Multiple consecutive calls to utils.api.cart.itemAdd not working

### ISSUE THREAD

**Issue by ovsokolov** [bigcommerce/stencil-utils#74]
Hi,

We are trying to issue several calls to utils.api.cart.itemAdd one after another. We dont see any errors and result returning has id, hash, and all other data generated by utils.api.cart.itemAdd. Please see atached
![add cart response log](https://user-images.githubusercontent.com/9545762/32661216-154e2524-c5f4-11e7-9054-22d94ef0b4c1.png)

But when we view the cart we don't see all items there. We actualy were never able to see all items it either 1 out of 3 added or 2 out of 3. Please see result after 3 items added we can only see 2, but same calls may generate only 1 item in the cart
![cart result](https://user-images.githubusercontent.com/9545762/32661269-5901d266-c5f4-11e7-9ec8-520b0e9bce6e.png)

**Comment by ovsokolov** [comment]
Issue resolved. Calls has to be done in synchronous mode. Looks like when its async it create multiple carts

**Comment by CurtisWist** [comment]
@ovsokolov Hi there, I'm having this same issue and was wondering if you could tell me exactly what you did to resolve it? I don't see an option to change the mode in utils.api.cart.itemAdd

**Comment by ovsokolov** [comment]
Thats not utils.api.cart.itemAdd option you have to control it yourself

**Comment by NjTheCoder** [comment]
Can you send the code example?
