### ISSUE TITLE
utils.api.product.getById not returning videos on localhost

### ISSUE THREAD

**Issue by ovsokolov** [bigcommerce/stencil-utils#81]
We are trying to retrieve product by ID using utils.api.product.getById and custom template with fromt-matter product: to display product information. When we run theme locally product.videos.list.length always 0. If we access same product just navigating to it on local host we can see videos. Also when we deploy it to bigcommerce product.videos.list.length  start working on api call. Its only not working if we call api on localhost

**Comment by ovsokolov** [comment]
other data like photo or description does return through API call on localhost

**Comment by davidwrpayne** [comment]
@ovsokolov I can't replicate this currently. If this is still an issue please comment and reopen.
